Feature/add users
Kotwic4/MapNotes-Backend pull request #7
Opened 2018-06-17 13:32 UTC by dykra

2018-06-17 17:09 UTC, Kotwic4 requested changes

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +     * Update or create map.
Trochę widać nie poprawioną copypaste

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +        return this.userRepository.findById(user.getId()).get();
W sumie możliwe że robiłęm analogicznie w mapie, ale wygląda to dość dziwnie. Trzeba by sprawdzić czy nie wystarczy zrobić 
```
return userRepository.save(user);
```

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/model/User.java
> +    private HashMap<String, Object> data;
Absolutnie bym tak nie robił. W przypadku mapy robiliśmy tak aby ułatwić sobie dodawanie atrybytów, ale nie było to do końca poprawne. Tak w przypadku hasła jest to absolutnie nie poprawne. Ponad to hasło użytkownika nigdy nie powino być a) odsyłana od serwera do użytkownika, b) trzymane w postaci jawnej.

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/model/UserRepository.java
> + * Repository which connect to database with information about {@link User maps}.
Znowu ewidetna copy pasta

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +    public User putUser(@Valid @RequestBody User user) {
Takie zapytanie umożliwia updatowanie czyjegoś konta(np zmianę hasła) nawet jak jesteśmy nie zalogowani. Generalnie nie powinno się zmieniać użytkowników innych niz samego siebie po przez API, chyba ze jest się addminem gdzie również powinno to być ograniczone

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +    public Boolean putUserIfNotInDatabase(@RequestBody User user) {
Wydaje mi się że chodzi tutaj o zwykła funkcje register user. W takim wypadku zwracał bym nowego użytkownika bo jes tam jego id, a sama informacja true/false nam wiele nie mówi. Ponad to zamiast false lepiej podać wyjątek z informacją co jest nie tak.

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +    public User getUserById(@PathVariable("userId") Long userId) throws UserNotFoundException {
Znowu wycieki informacji jak wyżej

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +    public void deleteUserById(@PathVariable("userId") Long userId) {
Pozwala na usuwanie dowolnego użytkownika.

2018-06-17 17:09 UTC, Kotwic4 commented on src/main/java/agh/edu/pl/MapNotes/controller/UserController.java
> +    public Boolean isUserCredentialsRight (@RequestBody User user) {
Nie wiem czy jest sens taką funkcje umieszczać jako API. Walidacja na froncie powina nie wymuszać co chwile zapytywania backendu, a jedynie ostateczna akcja powinna sprawdzać. Ponad to to co tutaj sprawdzacie nie jest rolą controllera tylko bardziej modelu/bazy danych. W szczególności że używacie tutaj funkcji podczas tworzenia użytkownika ale już podczas updateu nie.

2018-06-21 19:13 UTC, Ula2017 approved these changes

2018-06-21 19:13 UTC, merged